name: ci-test

on:
  push:
    branches: [master]
  pull-request:
    branches: [master]

jobs:
  name: Unit test
  runs-on: ubuntu-latest
  steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go
    - name: Checkout code into Go module directory
      uses: actions/checkout@v2
    - name: Test
      run: make test
